// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYZFiBpkeckd3CD2op3E_hnbuBr492RbA',
    appId: '1:990219204899:web:fa724f24361ed9f02a7496',
    messagingSenderId: '990219204899',
    projectId: 'travel-login-72e1a',
    authDomain: 'travel-login-72e1a.firebaseapp.com',
    storageBucket: 'travel-login-72e1a.appspot.com',
    measurementId: 'G-5V7ZGW7ZTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6IAZb2HZtgprZ1oV_TSgXuVdJZoVtD9I',
    appId: '1:990219204899:android:056904802bee38832a7496',
    messagingSenderId: '990219204899',
    projectId: 'travel-login-72e1a',
    storageBucket: 'travel-login-72e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTvuqqXSNuXT-A9-SokBZVWymDfLeCRMc',
    appId: '1:990219204899:ios:8e8c45b695ba6a602a7496',
    messagingSenderId: '990219204899',
    projectId: 'travel-login-72e1a',
    storageBucket: 'travel-login-72e1a.appspot.com',
    iosBundleId: 'com.exploreandtrip.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYZFiBpkeckd3CD2op3E_hnbuBr492RbA',
    appId: '1:990219204899:web:3cce1b52c9f6e0122a7496',
    messagingSenderId: '990219204899',
    projectId: 'travel-login-72e1a',
    authDomain: 'travel-login-72e1a.firebaseapp.com',
    storageBucket: 'travel-login-72e1a.appspot.com',
    measurementId: 'G-WXVDMLHXM2',
  );
}
